name: Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache dependencies
      - name: Cache Ruby gems
        uses: actions/cache@v4  # Mise à jour vers la version compatible Node.js 20
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Set up Node.js 20 (si nécessaire)
      - name: Set up Node.js
        uses: actions/setup-node@v4  # Mise à jour vers la version compatible Node.js 20
        with:
          node-version: '20'

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Change to your project's Ruby version

      # Install dependencies
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3


